<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Creates the products table with the natural-key unique constraint and
 * supporting indexes for filtering and reporting.
 */
final class Version20260615000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create products table';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform,
            'This migration targets PostgreSQL.'
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE products (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                external_id VARCHAR(191) NOT NULL,
                merchant_id VARCHAR(191) NOT NULL,
                name VARCHAR(500) NOT NULL,
                link VARCHAR(1000) NOT NULL,
                image_link VARCHAR(1000) DEFAULT NULL,
                price NUMERIC(12, 2) NOT NULL,
                original_price NUMERIC(12, 2) DEFAULT NULL,
                currency VARCHAR(3) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
            SQL);

        $this->addSql('CREATE UNIQUE INDEX uniq_merchant_external ON products (merchant_id, external_id)');
        $this->addSql('CREATE INDEX idx_products_currency ON products (currency)');
        $this->addSql('CREATE INDEX idx_products_price ON products (price)');
        $this->addSql('CREATE INDEX idx_products_name ON products (name)');

        $this->addSql("COMMENT ON COLUMN products.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN products.updated_at IS '(DC2Type:datetime_immutable)'");
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform,
            'This migration targets PostgreSQL.'
        );

        $this->addSql('DROP TABLE products');
    }
}
